#ifndef ASTEROIDS_ASSETS_H
#define ASTEROIDS_ASSETS_H
#include <stdint.h>
#define AST_SHIP_SPRITE_W 48
#define AST_SHIP_SPRITE_H 48
#define AST_SHIP_SPRITE_COUNT 8
#define AST_ROCK_LARGE_W 28
#define AST_ROCK_LARGE_H 28
#define AST_ROCK_MEDIUM_W 20
#define AST_ROCK_MEDIUM_H 20
#define AST_ROCK_SMALL_W 14
#define AST_ROCK_SMALL_H 14
#define AST_BULLET_SPRITE_W 16
#define AST_BULLET_SPRITE_H 16
#define AST_BULLET_SPRITE_COUNT 8
#define AST_EXPLOSION_SPRITE_W 32
#define AST_EXPLOSION_SPRITE_H 32
#define AST_EXPLOSION_SPRITE_COUNT 5
#define AST_POWERUP_SPRITE_W 18
#define AST_POWERUP_SPRITE_H 18
#define AST_POWERUP_SPRITE_COUNT 4
#define STRIKER_ENEMY_LIGHT_W 32
#define STRIKER_ENEMY_LIGHT_H 32
#define STRIKER_ENEMY_HEAVY_W 40
#define STRIKER_ENEMY_HEAVY_H 40
#define STRIKER_BOSS_W 96
#define STRIKER_BOSS_H 48
#define STRIKER_PLAYER_LASER_W 12
#define STRIKER_PLAYER_LASER_H 24
#define STRIKER_ENEMY_BULLET_W 8
#define STRIKER_ENEMY_BULLET_H 12
#define STRIKER_BOSS_SCATTER_BULLET_W 10
#define STRIKER_BOSS_SCATTER_BULLET_H 10
#define STRIKER_BOSS_HOMING_BULLET_W 12
#define STRIKER_BOSS_HOMING_BULLET_H 12
#define STRIKER_CHEST_W 24
#define STRIKER_CHEST_H 24
#define STRIKER_PLAYER_SHIP_W 48
#define STRIKER_PLAYER_SHIP_H 48
#define STRIKER_PLAYER_SHIP_COUNT 3
extern const uint8_t AST_SHIP_SPRITES[AST_SHIP_SPRITE_COUNT][AST_SHIP_SPRITE_W * AST_SHIP_SPRITE_H];
extern const uint8_t AST_ROCK_LARGE[AST_ROCK_LARGE_W * AST_ROCK_LARGE_H];
extern const uint8_t AST_ROCK_MEDIUM[AST_ROCK_MEDIUM_W * AST_ROCK_MEDIUM_H];
extern const uint8_t AST_ROCK_SMALL[AST_ROCK_SMALL_W * AST_ROCK_SMALL_H];
extern const uint8_t AST_BULLET_SPRITES[AST_BULLET_SPRITE_COUNT][AST_BULLET_SPRITE_W * AST_BULLET_SPRITE_H];
extern const uint8_t AST_EXPLOSION_SPRITES[AST_EXPLOSION_SPRITE_COUNT][AST_EXPLOSION_SPRITE_W * AST_EXPLOSION_SPRITE_H];
extern const uint8_t AST_POWERUP_SPRITES[AST_POWERUP_SPRITE_COUNT][AST_POWERUP_SPRITE_W * AST_POWERUP_SPRITE_H];
extern const uint8_t STRIKER_ENEMY_LIGHT[STRIKER_ENEMY_LIGHT_W * STRIKER_ENEMY_LIGHT_H];
extern const uint8_t STRIKER_ENEMY_HEAVY[STRIKER_ENEMY_HEAVY_W * STRIKER_ENEMY_HEAVY_H];
extern const uint8_t STRIKER_BOSS[STRIKER_BOSS_W * STRIKER_BOSS_H];
extern const uint8_t STRIKER_BOSS_DAMAGED[STRIKER_BOSS_W * STRIKER_BOSS_H];
extern const uint8_t STRIKER_PLAYER_LASER[STRIKER_PLAYER_LASER_W * STRIKER_PLAYER_LASER_H];
extern const uint8_t STRIKER_ENEMY_BULLET[STRIKER_ENEMY_BULLET_W * STRIKER_ENEMY_BULLET_H];
extern const uint8_t STRIKER_BOSS_SCATTER_BULLET[STRIKER_BOSS_SCATTER_BULLET_W * STRIKER_BOSS_SCATTER_BULLET_H];
extern const uint8_t STRIKER_BOSS_HOMING_BULLET[STRIKER_BOSS_HOMING_BULLET_W * STRIKER_BOSS_HOMING_BULLET_H];
extern const uint8_t STRIKER_CHEST[STRIKER_CHEST_W * STRIKER_CHEST_H];
extern const uint8_t STRIKER_PLAYER_SHIPS[STRIKER_PLAYER_SHIP_COUNT][STRIKER_PLAYER_SHIP_W * STRIKER_PLAYER_SHIP_H];
#endif
