#ifndef ASTEROIDS_BACKGROUND_H
#define ASTEROIDS_BACKGROUND_H

#include <stdint.h>

#define AST_BACKGROUND_W 240U
#define AST_BACKGROUND_H 240U
#define AST_BACKGROUND_PACKED_SIZE 28800U

extern const uint8_t AST_BACKGROUND_PACKED[AST_BACKGROUND_PACKED_SIZE];

#endif
